# Generated by Django 5.2.8 on 2025-11-19 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='skills_required',
            field=models.ManyToManyField(related_name='questions', to='questions.skill'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='questions_a_questio_fe80e9_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author'], name='questions_a_author__057c19_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='questions_q_categor_f1803c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_q_difficu_5db314_idx'),
        ),
    ]
